---
title: "prelimB"
format: docx
editor: visual
bibliography: references.bib
---

Although the relationship between place and health is well studied and measured, typical place-based measures of health represent a single time point without accounting for movement or mobility. Among the well-established understanding that place influences health is the understanding that place differentially impacts some groups of people more than others. For instance, a well cited paper from 2011 shows that **CURRENT KNOWLEDGE** What remains unknown is to what extent population mobility explains place-based health disparities. Thus, there is a critical need to assess the relationship between county-level patterns in mobility and county-level patterns in health factors and outcomes. Informed local policy making depends upon understanding mobility patterns. Without such knowledge, we cannot accurately quantify county-level health.

The long-term goal is to contribute to understanding the mechanisms by which mobility may be related to place-based health disparities so that local decision-makers may account for patterns in mobility when creating policy towards improved health for all people in all places. Our overall objective of this application is to quantify the relationship between county-level mobility and county-level health. Our central hypothesis is that poor county-level health factors and outcomes are associated with extremely high and extremely low rates of county-level mobility. We base this hypothesis on our preliminary findings that mobility patterns appear to be largely two-tailed. **MORE here** . The rationale for this project is that understanding the relationship between rural-urban mobility patterns is a necessary first step towards understanding rural-urban health disparities.

[**Aim 1:** Quantify the associations of place and self-reported mental health]{.underline}. **Hypothesis 1A:** There are statistically significant differences in rural and urban mental health after accounting for county-level demographic differences. **Hypothesis 1B:** The mediating effects of income inequality, social associations, access to exercise, food environment, mental health providers, air pollution, violent crime, and severe housing problems on the relationship between urbanicity and mental health are significantly different in rural counties than in urban counties after controlling for county-level sociodemographic factors.

[**Aim 2:** Estimate the effects of self-selected migration on county-level health]{.underline}. **Hypothesis 2A:** County-to-county migration does not occur at random. **Hypothesis 2B:** County-to-county migration patterns improve the predictability of autoregressive models of county-level measures of health, even after adjusting for spatial autocorrelation. **Hypothesis 2C:** The effect of intercounty migration on county-level health differs significantly between rural and urban counties.

[**Aim 3:** Identify counties, time periods, and sociodemographic groups that experience anomalous county-to-county migration patterns.]{.underline} Our working hypothesis is that extremely rural counties and extremely low income groups experience anomalous migration patterns.

At the conclusion of this work, we will be able to definitively state the relationship between population mobility and population health. We will have established rural-urban differences in health at a single time point, established rural-urban differences in health as they relate to mobility, and investigated outliers in the relationship between mobility and health. These findings will illuminate the mechanisms by which place-based health factors change as populations change. Understanding and quantifying county-level mobility is inherent to understanding and quantifying county-level health.

------------------------------------------------------------------------

#### [**Background and Significance**]{.underline}

Much of physical and mental health is place-based. There are well-established relationships between the built-environment and health outcomes. However, less is understood about how changes in place can affect health. Changes in place can occur both *to* and *by* people: when individuals relocate, not only do they experience a change in place, but they take their sociodemographic identities, income, health, employment, and education with them. As a result, the population, culture, and health of the place they are leaving and the place they are arriving changes, if only slightly. In aggregate, these migration-related changes could potentially affect the health of the population as a whole. In this proposal, we aim to measure the effects of migration on county-level measures of health. First, we study place-based determinants of mental health through the lens of urbanicity at a single time point. Then we assess the selection of migrants into and out of counties based on the health of each destination over time. Finally, we use a data science dimension reduction technique to determine which destinations, time periods, and demographic groups experience the most and least migration on average.

As individuals move from one place to another, the resources in their counties of origin and destination change. Therefore, the relationship between health and place can be viewed as "mutually reinforcing and reciprocal."[@cummins2007] For instance, when individuals relocate, they bring their social connections with them.[@dehaas2010] These social connections might lead to greater migration and more people (resources) in the future which could lead to better health outcomes on average and increased "pull" of the destination. The idea that migration can be self-perpetuating has been explored many times in the past[@dehaas2010a; @dehaas2021] mostly to describe "pull" factors -- factors that make a location more desirable after migration has occurred. The perceived average health of a community may be one of these "pull" factors.

Previous research has found that the health of migrants often differs from the average health of their origin and the average health of their destination. For instance, relocation from rural areas to urban areas has been associated with increased risk of CVD in some populations.[@miranda2011] Similarly, relocation to high-income countries has been associated with adverse cardiovascular health effects.[@agyemang2019] Several studies have found that rates of CVD are higher among migrants than among their peers who did not migrate.[@agyemang2022] For instance, a study of people who migrated to the US from Japan found that Japanese migrants to California had age-adjusted prevalence rates of CVD that were more than twice as high as their peers who migrated to Hawaii or did not migrate at all.[@marmot1975] This suggests that the average health of migratory populations becomes more similar to the average health of their destination than that of their origin, possibly because migrants take on the diets, habits, and other health factors of the place to which they relocate. Another possible explanation is that people who migrated from Japan to California were "pushed" to California while people who migrated from Japan to Hawaii were "pulled" to Hawaii.  

Income inequality has been found to be associated with poor health among some populations.[@zimmerman2006] Populations that experience high levels of income inequality may also experience declining rates of migration, as shown by Cooke 2013.[@cooke2013] Therefore, the effects of migration on health may be mediated by income inequality. Additionally, Lee's theory of migration suggests that regions with high levels of diversity are more likely to experience high rates of migration since migration is associated with imbalance between the origin and the destination and since diverse groups of people typically gravitate towards individuals like themselves.[@lee1966] Therefore, though perceived health may operate as a "pull" factor, not all people in a community are likely to experience improved health.  

There are many potential mechanisms by which urbanicity and the movement between urban centers could impact health. One might expect worse health in urban areas considering that limited access to green space [@tsai2018], concentration of populations marginalized from resources, crowded living conditions, and air pollution[@ha2017] are associated with negative health outcomes. On the other hand, urban populations are also more likely to have access to health care, more likely to participate in social organizations which offer psycho-social support [@yang2019], and more likely to have educational and financial opportunities [@ha2019], all of which are associated with positive health outcomes. A recently published paper assessing quality of life in Finland found higher rates of high quality of life in rural areas but not after controlling for perceived loneliness [@weckroth2022]. Another study found that people in urban areas have higher prevalence of both depression and anxiety despite having lower prevalence of other risk factors [@zijlema2015]. Disentangling the contribution of each of these potential mechanisms has important public health implications by pointing to possible solutions (e.g., increase access) for improving health. Relating urbanicity to health in the US, however, requires confronting several challenges. Urbanicity is a complex phenomenon, and its effects are impossible to isolate completely. There are many potential variables that confound the relationship between urbanicity and health. Most notably, counties that differ in urbanicity will also differ in the sociodemographic makeup of their population in terms of distributions of racial identity, age, income, and education. Even controlling for observed sociodemographic differences, there may still be *unobserved* confounding variables. For example, some people may choose to live in urban places and others in rural environments. These choices could be influenced by the past and present sociocultural context of each community which affects who feels welcomed into which communities. Factors such as personality and familial ties play large roles in both health and choice of living location [@chan1977]. Thus, analyses and conclusions must be carefully crafted to account for the complexity of where people live and why.

According to Lee's theory of migration [@lee1966], migration is selective, meaning that the individuals who migrate are not a random sample of the population of the origin. Migration occurs in response to a "push" or a "pull" -- migrants are "pushed" to leave an origin and "pulled" to a destination. "Pull" factors are more often associated with positive selection; migrants who are "pulled" to a destination due to perceived benefits are more likely to have high income or education status. Contrarily, migrants who are "pushed" to leave an origin are likely to have faced hardship in some form. In some cases, this is a negatively selected group including individuals who have lost jobs or suffered from climate change events; in other cases, an entire population may be "pushed" to migrate due to war or famine. Migration is often bimodal in that only the most advantaged and the least advantaged individuals relocate. This logic could be extended to the health distribution of migrants: only the most and least healthy individuals migrate. According to Norman and colleagues, migrants who move from more resource depleted regions to less resource depleted regions have better health on average than the population in their destination while migrants who move from less depleted regions to more depleted regions have worse health on average than the population in their destination [@norman2005]. Additionally, when the barriers between origin and destination are particularly high, migrants are often healthier on average than the people living in their destination, either because they have been selected through the migration process or because unhealthy people are less likely to choose to move when the barriers are high [@halliday2008]. Without understanding the individual decisions or circumstances that lead to migration, we cannot assess whether changes in health are the result of a "push" or a "pull." Disentangling the directionality of changes in health versus changes in migration is one challenge of using county-level data.

Since we propose an ecological study using county-level data, we can only adjust for county-level differences and cannot attempt to measure individual-level differences. County-level data can be useful to understand how place is related to average health. In particular, county-level analyses may be useful in informing local policies to raise the *average* health of a county, and county-level sociodemographic analyses may be useful in informing local policies to reduce disparities within a county -- thus, county-level analyses are useful in addressing both of the primary goals of population health: increasing the health of the population overall and reducing health disparities [@kindig2017]. As we have seen during the COVID pandemic, local public health departments, school boards, and faith-based organizations have the power to make decisions which affect public health at an "average" level. County-level analyses may help local decision-makers understand the patterns and processes of their communities. Additionally, because we use a dataset which contains all 3142 US counties, rural counties are better represented than urban counties despite having smaller total population.

#### [**Innovation**]{.underline}

The relationship between place and health has been studied many times before. However, many existing studies measure the effects of place on health at a single point in time, without accounting for interconnectedness via migration. Additionally, though time-series forecasting of county-level mortality rates has been done many times previously, our *migrationally* autoregressive model (which accounts for county-to-county migration rates) is unique -- many existing models account for spatial correlation between counties but do not account for migration rates between counties. There are many dimensions of migration: time, space, age, neighborhood, health, income, etc. In our third aim, tensor factorization allows us to assess each dimension of migration separately. Tensor factorization has been used to study migration using the IRS migration flow dataset, but to our knowledge, it has not yet been used to assess sociodemographic dimensions of migration. Our application of tensor factorization will allow us to create a better picture of who migrates, when they migrate, and where they migrate on average within the US which we can then use to study the relative effect of migration on county-level health.

#### [**Approach**]{.underline}

[**Aim 1:** Quantify the associations of place and self-reported mental health.]{.underline} **Hypothesis 1A:** There are statistically significant differences in rural and urban mental health after accounting for county-level demographic differences. **Hypothesis 1B:** The mediating effects of income inequality, social associations, access to exercise, food environment, mental health providers, air pollution, violent crime, and severe housing problems on the relationship between urbanicity and mental health are significantly different in rural counties than in urban counties after controlling for county-level sociodemographic factors.  

This aim is complete. Olson-Williams, H.E., Grey, S.T., and Cochran, A.L. have published a manuscript titled "Ecological Study of Urbanicity and Self-reported Poor Mental Health Days Across US Counties" in the Community Mental Health Journal. Please refer to the published paper [here](https://doi.org/10.1007%2Fs10597-022-01082-x).

[Data]{.underline}: Data on US counties was provided by the University of Wisconsin's County Health Rankings and Roadmaps (CHRR). CHRR collects and aggregates publicly available data at the county-level. Therefore, this is an ecological study, and the unit of analysis for this paper is a county. We analyzed the 2021 CHRR dataset for all 3142 US counties for which data is available. The primary exposure is urbanicity. Each county in the dataset has been assigned an urbanicity category based on the 2013 National Center for Health Statistics (NCHS) Urban--Rural Classification Scheme for Counties (Rothwell et al., n.d.). The NCHS urban--rural classification scheme relies on information such as population density as well as proximity to the largest city within a metropolitan statistical area. The six categories are as follows: large central metro (n = 68), large fringe metro (n = 368), medium metro (n = 372), small metro (n = 357), micropolitan (n = 641), and noncore (n = 1335). It is worth noting that the four "Metro" categories contain 85% of the total US population.

The **primary outcome of interest is poor mental health days**, an age-adjusted average number of mentally unhealthy days reported in the past 30 days. This is a self-reported variable collected by the BRFSS. The most recent available data represents 2018. We chose to use this measure of self-reported health because BRFSS is the largest continuously conducted health survey system in the world (CDC - About BRFSS, 2019), and BRFSS county-level estimates span all 3142 US counties. These estimates are well-validated and commonly used (Pierannunzi et al., 2013).

We controlled for several variables that might confound the relationship between urbanicity and mental health. Broadly, the sociodemographic makeup of a county varies with urbanicity and is expected to also influence mental health of persons living in the county. The first variable we controlled for is median household income: the income level at which half of households in the county earn more, to measure the typical income in a county. We controlled for median household income, since higher income allows county residents to enjoy greater access to mental health care, which may be positively related to mental health (Grembowski et al., 2002). For similar reasons, we also controlled for education (Chevalier & Feinstein, 2006). Thus, the second control variable was some college: the percentage of adults ages 25--44 with some post-secondary education. The third control variable was percent over 65: the percentage of the population that are over age 65, since age is associated with decreased rates of self-reported poor mental health (NIMH» Mental Illness, n.d.). Another control variable was US state. We added a control variable for state to account for potential state-level effects since our outcome variable comes from BRFSS which uses state-level sampling methods.

We also controlled for race/ethnicity since self-reported mental health differs by race/ethnicity. For example, during the pre-vaccine COVID-19 pandemic, adults identifying as Hispanic had 20% to 400% greater odds of experiencing poor mental health than adults identifying as non-Hispanic (Lee & Singh, 2021). Additionally, people who identify as Black are historically more likely to report lower levels of life satisfaction than people identifying as white (Hughes & Thomas, 1998). Therefore, we controlled for the variables Percent Black: the percentage of the population that is non-Hispanic Black or African American, and Percent Hispanic: the percentage of the population that is Hispanic.

**We examined eight potential mediators**. Social associations is the number of membership associations in a county per 10,000 population. Access to exercise is the percentage of the population with adequate access to locations for physical activity. Food environment index is calculated as a ratio of the percent of each county's population experiencing limited access to healthy foods to the percent of each county's population experiencing food insecurity. The percent of the population experiencing limited access to health foods is calculated as a function of poverty and distance to a grocery store while food insecurity is a modeled estimate from the Core Food Insecurity Model (Map the Meal Gap Data \| Feeding America, n.d.). Mental health providers is the ratio of population to mental health providers. Air pollution is the average daily density of fine particulate matter in micrograms per cubic meter. Violent crime is the number of reported violent crime offenses per 100,000 population. Severe housing cost burden is the percentage of households that spend 50% or more of their income on housing. Income inequality is the ratio of household income at the 80th percentile to income at the 20th percentile.

[Approach:]{.underline} We estimated the average relationship between urbanicity and poor mental health days using mixed effects linear regression models. For simplicity, we built models that compare counties from one urbanicity category at a time against small metro counties. Hence, five comparisons were made: large central metro, large fringe metro, medium metro, micropolitan, and noncore vs. small metro. Each linear regression model included poor mental health days as the dependent variable and urbanicity as the independent variable. State was included as a random effect to accommodate within-state correlation and variation due to state differences in BRFSS approaches. Models were fit with and without adjustments for the control variables. Control variables were accounted for using inverse probability weighting (IPW). IPW entails weighting each county by the multiplicative inverse of the propensity scores, i.e., the probability of belonging to the county's urbanicity category conditional on the confounding variables (i.e., education, income, age, percent Black, and percent Hispanic). This approach was used as opposed to including control variables directly in the model to avoid issues with misspecification of their influence in the linear regression model. Propensity scores needed for IPW were calculated from a logistic regression model for each urbanicity comparison. Hence, five logistic regression models were fit. Small metro was chosen as the reference category to avoid propensity scores near 0 or 1, since small metro is one of the middle urban categories. By contrast, an urban category at one extreme (e.g., large central metro) would lead to propensities close to 0 or 1 when compared to the other extreme (e.g. noncore). Education, income, percent Black, percent Hispanic, and age are treated as independent variables in each logistic regression model. Considering that education and income have a strong relationship to mental health (Araya et al., 2003) and vary greatly across counties, an interaction term between income and education is included in the logistic regression model. In addition, natural cubic splines with three degrees of freedom each were used for education and household income. To validate this choice of model, other models were considered and compared to our model based on Akaike Information Criteria (AIC). We examined eight potential mediators using a combination of inverse probability weighting and random effects to account for potential confounders of the urban-mental health relationship. Mediation analysis was conducted in two steps [@imai2010] [@vanderweele2014] (Imai et al., [2010](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9838413/#CR22); VanderWeele & Vansteelandt, [2014](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9838413/#CR48)). First, we built a linear regression model for each urbanicity comparison relating potential mediators and urbanicity to poor mental health. These models included the eight mediators as independent variables but were otherwise identical to models from our primary analysis: poor mental health days was the dependent variable, urbanicity was an independent variable, state was a random effect, and IPW was used to adjust for control variables. Second, we built a linear regression model for each urbanicity comparison and each potential mediator. In this case, the potential mediator was the outcome variable, urbanicity was the independent variable, state was a random effect, and IPW was used to adjust for control variables. 

[Results and future directions]{.underline}: Controlling for state, age, income, education, and race/ethnicity, large central metro counties reported 0.24 fewer average poor mental health days than small metro counties (*t* = − 5.78, *df* = 423, *p* \< .001). Noncore counties had 0.07 more average poor mental health days than small metro counties (*t* = 3.06, *df* = 1690, p = 0.002). Better mental health in large central metro counties was partly mediated by differences in the built environment, such as better food environments. Poorer mental health in noncore counties was not mediated by considered mediators. Our findings shed light on contemporary questions about mental health in the US. Is mental health better or worse in urban areas than rural areas? There are arguments on both sides: urban areas have greater access to resources like mental health providers and social associations, but rural areas have less violent crime or income inequality and greater access to green spaces. Finding that urban counties are associated with better, not worse, mental health is contrary to what might be expected based on what we know from different countries and earlier time periods. For example, a study published in 2000 of urban--rural mental health differences in Great Britain found that individuals living in urban centers had higher rates of three indicators of poor mental health (Paykel et al., [2000](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9838413/#CR35)), and a 2007 study of Chinese migrant workers found that workers living in urban areas had worse mental health than workers in rural areas (Li & Rose, [2017](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9838413/#CR28)). Thus, there appear to be unique factors at play when it comes to mental health in contemporary US. In our next two aims, we use migration as a possible explanation for these US-specific differences in the relationship between place and health.   

Restate aims from above; put all hypotheses in one clump; add variable description (in a table?) exposure, outcome, etc  ; include regression model equations in approach- three models, one for each hypothesis, add table 1 for all data   

[**Aim 2:** Estimate the effects of self-selected migration on county-level health**.**]{.underline} **Hypothesis 2A:** County-level migration does not occur at random. **Hypothesis 2B:** County-to-county migration patterns improve the predictability of autoregressive models of county-level measures of health. **Hypothesis 2C:** The effect of intercounty migration on county-level health differs significantly between rural and urban counties.

[Data:]{.underline} To study the relationship between health and migration, we use county-level estimates of age-adjusted mortality available through CDC WONDER joined with IRS county-to-county migration flow data. Data for mortality is historically easier to collect and more accurate than other measures of human health. CITE Death has a clear and common definition making it possible to consistently estimate mortality rates across countries, health systems, and time periods. CITE. Mortality as a measure of length of life also has important policy and health equity implications and can be used to assess which individuals or groups are likely to live longest and which individuals or groups may be most in need of additional care. Data represent the years 2011 through 2019. We chose to remove the year 2020 from our dataset because across the US, the median county-level mortality rate rose from 713.2 per 100,000 in 2019 to 828.5 per 100,000 in 2020. This unprecedented change in mortality is difficult to model since it occurred so unpredictably **citations here from other studies that have removed 2020 data???** IRS migration data are available for 1990 through 2019. However, in 2011, the IRS changed their methods to produce migration estimates based on a full year of income tax filings rather than a partial year. Prior to 2011, migration estimates represented between 95 and 98 percent of total annual income tax filings and excluded income taxes filed after September of each calendar year^15^; estimates after 2011 include all annual income tax filings collected for each year. Therefore, we have chosen only to include data after the 2011 change in IRS methodology. One final limitation of IRS data (which we are attempting to leverage as a strength in our analyses) is that households that do not file tax returns cannot be included in migration estimates. Therefore, university students, low-income households, and workers who receive informal wages are systematically missing from IRS migration estimates. These individuals may be more likely to be included in ACS and Census estimates^16^ (which we use in Aim 3) though no population estimate is perfect. Because IRS county-to-county migration data includes only individuals who file taxes with the US government both before and after they migrate, we assume that individuals represented in the IRS migration flows data are less likely to be pushed to migrate by potentially health-related factors such as violence, famine, and corruption than individuals who migrate but are excluded from the IRS data. Therefore, any differences in changes in health between counties may be the result of self-selection by IRS-represented migrants or health-related selection by nonIRS-represented migrants. Despite these limitations, IRS migration data has been used many times in the past to complete complex and accurate analyses of US migration patterns. For instance, IRS migration flow data has been used to estimate the effects of sea-level rise on geographic distribution of the US population,^17^ measure recovery after Hurricanes Katrina and Rita^18^, and assess the economic impacts of migration resulting from environmental hazards^19^.

[Approach]{.underline}: Autoregressive models have commonly been used to estimate mortality rates; for instance, in a 2011 paper, county-level mortality was modeled using spatial autoregressive models in which each county's relative position to other counties as well as its historical mortality rates were considered (Yang, Jensen, Haran). Another similar paper (Sparks and Sparks) used an autoregressive model with county-level estimates of mortality that were standardized for measures of income and employment, population density and rurality, and race/ethnicity. Similarly, early in the COVID-19 pandemic, researchers used a spatial autoregressive model to assess the relationships between county-level COVID-19 mortality rates and county-level sociodemographic characteristics (Fielding-Miller, Sundaram, Brouwer). This method has also been extended to age-group and country-level data to explain cohort effects within countries. (Li and Lu 2017) Finally, a 2020 paper adapted this method using age-group data to estimate country-level life expectancy more efficiently, more accurately, and with greater precision for younger populations (Shi). In this aim, we extend previous autoregressive models to account for county interconnectedness. Our **primary outcome of interest is county-level age-adjusted mortality**, which we predict using a combination of lagged county-level mortality, spatial autocorrelation (Moran's I), and migration. To quantify migration, we develop a novel "migration term" which accounts for the mortality rates of individuals who have moved to a county of interest during a given period, essentially a weighted average of the mortality rates of all the origin counties. This approach requires the assumption that all migration occurs at random - ie the average mortality rate of any group of migrants from a specific origin county is approximately equivalent to the mortality rate of their origin county. We calculated the following for each change in year and for each destination county

$$ 
migration_{it} = \frac{ \sum_{i=1}^{k} out_o rate_{o,t-1} + rate_{i,t-1} (pop_{i, t-1} - out_i)}{ \sum_{i=1}^{k}  out_o + (pop_{i,t-1} - out_i)}
$$

where\
$out_o$ represents the number of migrants from a unique origin county $o$ who migrated to a destination county $i$ between year $t$ and year $t-1$. \
$rate_{o,t-1}$ is the mortality rate of an unique origin county $o$ at initial year $t-1$\
$rate_{i, t-1}$ is the mortality rate of an unique destination county $i$ at initial year $t-1$\
$pop_{i, t-1}$ is the population of an unique destination county $i$ at initial year $t-1$\
$out_i$ is the number of migrants who left each unique destination county $i$ between year $t$ and year $t-1$.

Note that we complete all analyses from the perspective of a "destination" county. To simplify things, we have chosen to focus on the effects of migration to a destination rather than away from an origin. We used a multilevel autoregressive model to explain county age-adjusted mortality rates across 3000 US counties. We tested several models and used BIC to determine the best fitting model. BIC is commonly used to determine models with greatest explanatory power (CITE). Our initial model included a random intercept for each destination county and random slope for each time covariate. We included random intercepts for each destination county in an attempt to account for some variation between counties, as recommended by Greenland and Morgenstern's assessment of best practices for ecological studies[@greenland1989]. We then iteratively added splines for the prior year's average county-level mortality rate and the migration term. Our initial model is similar to autoregressive county-level mortality models used by [@sparks2010](Sparks and Sparks), (Yang, Jensen, Haran), and (Fielding-Miller, Sundaram, Brouwer).

```{r prepare data, include = FALSE, message = FALSE, warning = FALSE}
library(dplyr)
library(ggplot2)
load("data_processed/migtree.Rdata") #this dataset is called ppu2 for some reason 
#urb codes are here already 
#this contains data for 12 unique time periods: 0809 through 1920 


load("data_processed/migterm.Rdata") # this dataset is called migterm 
#this contains data for 2011 through 2019 



#need to remove years prior to 2011 due to IRS methodology change 
netmig = ppu2 %>% filter(year>=1112 & year <= 1819)  %>% 
  group_by(origid, urbcode) %>% summarise(totmig = sum(pn_mig))
#totmig = the total number of years that an origid had net migration between 1011 and 1819 (ie 9 unique time periods)


#need to remove years prior to 2011 due to IRS methodology change 
migterm = migterm %>% filter(lagyear >=2011)

netmigterm = merge(migterm, netmig, by.x = "destid", by.y = "origid", all.x = TRUE)
#there are 22 obs lost during this merge (5 unique destids) 
#these are the result of fipscodes changes - they can be corrected later; ignoring for now since it's already impossible to have a perfect 3142 county dataset 
netmigterm = netmigterm[!is.na(netmigterm$urbcode),] 
netmigterm = netmigterm[!is.na(netmigterm$migterm),] #none lost during this step 
netmigterm = netmigterm[!is.na(netmigterm$totmig),] #none lost during this step 

summary(netmigterm$totmig)


# WITHOUT RACE - TOTAL COUNTY VALUES ONLY 

library(splines)
library(lme4)

migmodm = netmigterm %>% arrange(year) %>% 
  group_by(destid) %>% 
  filter(n_distinct(totrate_d1)>4)


migmtemp = na.omit(migmodm) #no additional NAs removed  
mn = data.frame(migmodm)

mnn = mn %>% 
 arrange(year) %>% 
 group_by(destid) %>% 
 mutate(t = row_number())

mnn$ft = as.factor(mnn$t)

# i rescaled these vars once to confirm that the results were unchanged by the "Warning: Some predictor variables are on very different scales: consider rescaling" message 
# bic values were slightly different using standardized values, but their pattern/relative order did not change 
# mnn$totrate_d0 = scale(mnn$totrate_d0)
# mnn$migterm = scale(mnn$migterm)
# mnn$totmig = scale(mnn$totmig) 




#(1|fips) is a random intercept; each fips's reg line is shifted up/down randomly with mean 0
#(1+time|fips) includes a random slope for time; the effect of time differs randomly from fips to fips 

mmig = lme4::lmer(totrate_d1 ~ ft + (1+t|destid) + migterm, data = mnn,
                control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

mnon = lme4::lmer(totrate_d1 ~ ft + totrate_d0 + (1+t|destid), data = mnn,
                control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

mboth = lme4::lmer(totrate_d1 ~ ft + totrate_d0 + (1+t|destid) + migterm, data = mnn,
                control=lmerControl(optimizer="bobyqa",optCtrl=list(maxfun=2e5)))

AIC(mmig, mnon, mboth)
```

To test Hypothesis 2A: county-to-county migration does not occur at random, we compare a model using our weighted average migration term, which represents migration at random, to a model that includes only the prior year's average county-level mortality rate. The full model is shown below:

$$ 
y_{i} = \beta_0 + (\beta_{13} + \upsilon_{13ij})t_{13i} + (\beta_{14} + \upsilon_{14ij})t_{14i} + (\beta_{15} + \upsilon_{15ij})t_{15i}  + (\beta_{16} + \upsilon_{16ij})t_{16i} + (\beta_{17} + \upsilon_{17ij})t_{17i} + (\beta_{18} + \upsilon_{18ij})t_{18i} + (\beta_{19} + \upsilon_{19ij})t_{19i} + \beta_m m_i + \beta_r r_{n-1,i} + \mu_j + \epsilon_{ij}  
$$ Alternatively we can write this as $$ 
y_{i} = \beta_0 + \sum_{n=12}^{19}{{(\beta_n + \upsilon_{nij})t_{ni} }}+ \beta_m m_i + \beta_r r_{n-1,i} + \mu_j + \epsilon_{ij}  
$$

$$ 
y_{it} = \beta_0 + \beta_{13i}t_{13} + \beta_{14i}t_{14} + \beta_{15i}t_{15}  + \beta_{16i}t_{16} + \beta_{17i}t_{17} + \beta_{18i}t_{18} + \beta_{19i}t_{19} + \beta_m m_i + \beta_r r_{n-1,i} + \mu_{it} + \epsilon_{ij}  
$$

where\
$y_{ij}$ represents the predicted age-adjusted mortality rate of each county $i$\
$\beta_{ni}$ are estimated differences in the age-adjusted mortality rate of each county $i$ at year $t_{n}$ compared to year 2012\
$m_i$ is the weighted average migration term for each county $i$ **AT YEAR ???**\
$r_{n-1,i}$ is the lagged age-adjusted mortality rate for each county $i$ at year $n-1$ \
$\mu_i$ is a random intercept for each county $i$ and\
$\upsilon_{nij}$ is a random slope for the effect of each year $n$ on each county $i$\

or Alternatively, we could specify this like Sparks and Sparks with a big matrix of coeffs Y = XBeta + e

need to put upsilon elsewhere since there is only 1 time (continuous)

the other ts need to be binary

i propose:

a multilevel model: first we develop a county-specific relationship between mortality and migration then we use this modelled migration-mort term in an autoregressive model which may or may not need "time" as a factor variable

OR at the very least, it seems maybe the migterm should have the random slope instead of each time factor??

I want to redo these modelling decisions and instead create multilevel models similar to sparks and sparks (https://doi-org.ezproxy.library.wisc.edu/10.1002/psp.564): first we develop a county-specific relationship between mortality and migration, then we use this modelled migration-mort term in an autoregressive model which may or may not need "time" as a factor variable At the very least, it seems maybe the migterm should have the random slope instead of each time factor??

I think we need a spatial autoregressive term (moran's I) - then we can show that the relationship between migration and mortality is not just residual spatial correlation / we can show that spatial correlation is actually migration (seems like maybe something similar could have been done before but I have not yet found it)

Referencing https://www.econometrics-with-r.org/10-4-regression-with-time-fixed-effects.html:

time as a factor is useful when we want to control for variables that are consta

This could change everything subsequent...... not sure about time constraints - keep pushing with previous models despite reservations? cannot remember the rationale behind treating time as a factor variable

To test Hypothesis 2B: County-to-county migration patterns improve the predictability of autoregressive models of county-level measures of health, we compare a series of autoregressive models, including terms for several different methods of measuring migration.

Finally, to test Hypothesis 2C: The effect of intercounty migration on county-level health differs significantly between rural and urban counties, we add rural/urban terms to the models used to test Hypothesis 2B.

[Results and future directions:]{.underline} We found that models including our weighted average migration term did not have as much explanatory power as models that included only the prior year's average county-level mortality rate. This suggests that migration does not occur at random - if migration occurred at random, we would expect a weighted average of the expected mortality rates of all potential migrants to be equivalent, if not more predictive, of the future mortality than the prior year's mortality rate. Therefore, Hypothesis 2A holds.

When we included the prior year's average county-level mortality rate in addition to our weighted average migration term, our model had greater explanatory power than a model including only the prior year's mortality rate.

------------------------------------------------------------------------
